# Definition of various test suites
testsuite_1:
  test_configs:                 # You have to define at least one test_config
    - test1
  robots:                       # You have to define at least one robot
    
    
    - gaussianRange_0.05m_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_0.1m_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_0.25m_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_0.5m_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_0.75m_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_1.0m_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_1.25m_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_1.5m_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_0.05m_no_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_0.1m_no_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_0.25m_no_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_0.5m_no_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_0.75m_no_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_1.0m_no_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_1.25m_no_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_1.5m_no_ndt_mapping_no_ndt_matching_0.02_0
    - standard_0.05m_ndt_mapping_no_ndt_matching_0.02_0
    - standard_0.1m_ndt_mapping_no_ndt_matching_0.02_0
    - standard_0.25m_ndt_mapping_no_ndt_matching_0.02_0
    - standard_0.5m_ndt_mapping_no_ndt_matching_0.02_0
    - standard_0.75m_ndt_mapping_no_ndt_matching_0.02_0
    - standard_1.0m_ndt_mapping_no_ndt_matching_0.02_0
    - standard_1.25m_ndt_mapping_no_ndt_matching_0.02_0
    - standard_1.5m_ndt_mapping_no_ndt_matching_0.02_0
    - standard_0.05m_no_ndt_mapping_no_ndt_matching_0.02_0
    - standard_0.1m_no_ndt_mapping_no_ndt_matching_0.02_0
    - standard_0.25m_no_ndt_mapping_no_ndt_matching_0.02_0
    - standard_0.5m_no_ndt_mapping_no_ndt_matching_0.02_0
    - standard_0.75m_no_ndt_mapping_no_ndt_matching_0.02_0
    - standard_1.0m_no_ndt_mapping_no_ndt_matching_0.02_0
    - standard_1.25m_no_ndt_mapping_no_ndt_matching_0.02_0
    - standard_1.5m_no_ndt_mapping_no_ndt_matching_0.02_0
    - gaussianRange_0.05m_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_0.1m_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_0.25m_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_0.5m_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_0.75m_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_1.0m_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_1.25m_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_1.5m_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_0.05m_no_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_0.1m_no_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_0.25m_no_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_0.5m_no_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_0.75m_no_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_1.0m_no_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_1.25m_no_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_1.5m_no_ndt_mapping_no_ndt_matching_0.02_1
    - standard_0.05m_ndt_mapping_no_ndt_matching_0.02_1
    - standard_0.1m_ndt_mapping_no_ndt_matching_0.02_1
    - standard_0.25m_ndt_mapping_no_ndt_matching_0.02_1
    - standard_0.5m_ndt_mapping_no_ndt_matching_0.02_1
    - standard_0.75m_ndt_mapping_no_ndt_matching_0.02_1
    - standard_1.0m_ndt_mapping_no_ndt_matching_0.02_1
    - standard_1.25m_ndt_mapping_no_ndt_matching_0.02_1
    - standard_1.5m_ndt_mapping_no_ndt_matching_0.02_1
    - standard_0.05m_no_ndt_mapping_no_ndt_matching_0.02_1
    - standard_0.1m_no_ndt_mapping_no_ndt_matching_0.02_1
    - standard_0.25m_no_ndt_mapping_no_ndt_matching_0.02_1
    - standard_0.5m_no_ndt_mapping_no_ndt_matching_0.02_1
    - standard_0.75m_no_ndt_mapping_no_ndt_matching_0.02_1
    - standard_1.0m_no_ndt_mapping_no_ndt_matching_0.02_1
    - standard_1.25m_no_ndt_mapping_no_ndt_matching_0.02_1
    - standard_1.5m_no_ndt_mapping_no_ndt_matching_0.02_1
    - gaussianRange_0.05m_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_0.1m_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_0.25m_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_0.5m_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_0.75m_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_1.0m_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_1.25m_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_1.5m_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_0.05m_no_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_0.1m_no_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_0.25m_no_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_0.5m_no_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_0.75m_no_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_1.0m_no_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_1.25m_no_ndt_mapping_no_ndt_matching_0.02_2
    - gaussianRange_1.5m_no_ndt_mapping_no_ndt_matching_0.02_2
    - standard_0.05m_ndt_mapping_no_ndt_matching_0.02_2
    - standard_0.1m_ndt_mapping_no_ndt_matching_0.02_2
    - standard_0.25m_ndt_mapping_no_ndt_matching_0.02_2
    - standard_0.5m_ndt_mapping_no_ndt_matching_0.02_2
    - standard_0.75m_ndt_mapping_no_ndt_matching_0.02_2
    - standard_1.0m_ndt_mapping_no_ndt_matching_0.02_2
    - standard_1.25m_ndt_mapping_no_ndt_matching_0.02_2
    - standard_1.5m_ndt_mapping_no_ndt_matching_0.02_2
    - standard_0.05m_no_ndt_mapping_no_ndt_matching_0.02_2
    - standard_0.1m_no_ndt_mapping_no_ndt_matching_0.02_2
    - standard_0.25m_no_ndt_mapping_no_ndt_matching_0.02_2
    - standard_0.5m_no_ndt_mapping_no_ndt_matching_0.02_2
    - standard_0.75m_no_ndt_mapping_no_ndt_matching_0.02_2
    - standard_1.0m_no_ndt_mapping_no_ndt_matching_0.02_2
    - standard_1.25m_no_ndt_mapping_no_ndt_matching_0.02_2
    - standard_1.5m_no_ndt_mapping_no_ndt_matching_0.02_2
  robot_envs:                   # You have to define at least one robot_env
    - env1
